// Package contract owns the embedded canonical agent-runtime contract.
//
// The contract.md file in this directory is the source of truth for what
// agents see when they call `sparks describe` or read the per-agent
// instruction file generated by `sparks init --agent X`. The repo-root
// `sparks-contracts.md` is a synced copy for GitHub readability — keep
// the two in sync via `make sync-contract` (or a CI check).
//
// Why embedded: the design doc (Approach B / "self-teaching runtime")
// makes the binary the authoritative source of the protocol. A new agent
// dropped into a vault asks `sparks describe` and gets the same contract
// the binary actually implements — not whatever prose someone copied
// into a stale CLAUDE.md.
package contract

import _ "embed"

//go:embed contract.md
var contractMarkdown string

// Markdown returns the full canonical contract as markdown text. The
// returned string is safe to print directly to stdout or pipe into a
// per-agent instruction file.
func Markdown() string { return contractMarkdown }

// AgentName is one of the recognized harness identifiers passed to
// `sparks init --agent X`. New agents are added by appending to
// AgentFilenames; the contract content is the same across all of them.
type AgentName string

const (
	AgentClaude  AgentName = "claude"
	AgentCodex   AgentName = "codex"
	AgentGemini  AgentName = "gemini"
	AgentGeneric AgentName = "generic"
)

// AgentFilenames maps each known harness to the conventional filename
// that harness reads at vault root for system-prompt-like instructions.
// `codex` and `generic` both use AGENTS.md (the open standard); init
// is idempotent and skips an existing file unless --force is set.
var AgentFilenames = map[AgentName]string{
	AgentClaude:  "CLAUDE.md",
	AgentCodex:   "AGENTS.md",
	AgentGemini:  "GEMINI.md",
	AgentGeneric: "AGENTS.md",
}

// KnownAgents is the stable list of agents the CLI accepts for
// --agent. Order matters for help text.
var KnownAgents = []AgentName{
	AgentClaude,
	AgentCodex,
	AgentGemini,
	AgentGeneric,
}

// Filename returns the conventional filename for the given agent, or
// the empty string if name isn't recognized.
func Filename(name AgentName) string { return AgentFilenames[name] }

// IsKnown reports whether name matches one of the recognized agents.
func IsKnown(name AgentName) bool {
	_, ok := AgentFilenames[name]
	return ok
}
