package collections

import (
	"fmt"
	"strings"
	"time"
)

// header is the shared frontmatter + intro for every regenerated
// collection. We mark these explicitly as type=collection and seed-as-
// generated so the lint checks don't fire on them.
//
// IMPORTANT: every regenerated collection page starts with this exact
// banner so users (and grep) can immediately see "this file is rebuilt
// by `sparks collections regen` — don't hand-edit."
func header(name string) string {
	today := time.Now().UTC().Format("2006-01-02")
	return fmt.Sprintf(`---
title: %s
type: collection
maturity: stable
sources: []
created: %s
updated: %s
---

<!-- AUTO-GENERATED by sparks collections regen — do not edit. -->

# %s

`, name, today, today, name)
}

// trailer adds a tiny note at the bottom of the page so anyone reading
// the file in Obsidian sees the regen warning twice (top + bottom).
func trailer() string {
	return "\n_Auto-generated by `sparks collections regen`._\n"
}

// titleFromFilename derives a display title from a markdown filename:
// "BigQuery Optimization.md" → "BigQuery Optimization".
func titleFromFilename(path string) string {
	name := pathBase(path)
	name = strings.TrimSuffix(name, ".md")
	return name
}

// pathBase is filepath.Base inlined so this file imports nothing fancy.
func pathBase(p string) string {
	for i := len(p) - 1; i >= 0; i-- {
		if p[i] == '/' || p[i] == '\\' {
			return p[i+1:]
		}
	}
	return p
}
