package core

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/yogirk/sparks/internal/manifest"
	"github.com/yogirk/sparks/internal/vault"
)

// IndexResult summarizes what `sparks index` did.
type IndexResult struct {
	OutputPath        string         `json:"output_path"`
	Bytes             int            `json:"bytes"`
	PagesByType       map[string]int `json:"pages_by_type"`
	DescriptionsKept  int            `json:"descriptions_kept"`
	DescriptionsBlank int            `json:"descriptions_blank"`
	DryRun            bool           `json:"dry_run,omitempty"`
}

// existingEntryRE captures lines in an existing wiki/index.md that follow
// the canonical format: `- [[Title]] — description (N sources)` or
// `- [[Title]] — description`. We capture title + description so the
// rebuild preserves any agent-authored descriptions.
var existingEntryRE = regexp.MustCompile(`^\s*-\s*\[\[([^\]|#]+?)(?:\|[^\]]*)?\]\]\s*[—-]?\s*(.*?)(?:\s*\(\d+\s+sources?\))?\s*$`)

// Index rebuilds wiki/index.md from manifest state. Existing
// agent-authored descriptions are preserved by matching on title.
//
// Layout: a level-1 H1, then one section per page type in fixed order
// (entities → concepts → synthesis → summaries → collections), then the
// Tasks pointer (Tasks.md is a live page, not a generated entry).
func Index(v *vault.Vault, dryRun bool) (IndexResult, error) {
	db, err := manifest.Open(v.ManifestPath())
	if err != nil {
		return IndexResult{}, err
	}
	defer db.Close()
	pages, err := db.ListPages()
	if err != nil {
		return IndexResult{}, err
	}

	indexPath := filepath.Join(v.Root, "wiki", "index.md")
	descriptions := readExistingDescriptions(indexPath)

	byType := groupByType(pages)

	var body strings.Builder
	body.WriteString("# Wiki Index\n\n")
	body.WriteString("Auto-generated by `sparks index`. Page descriptions are preserved across rebuilds — edit them inline and they'll survive the next regen.\n\n")

	result := IndexResult{
		OutputPath:  indexPath,
		PagesByType: map[string]int{},
		DryRun:      dryRun,
	}

	for _, t := range []string{"entity", "concept", "synthesis", "summary", "collection"} {
		list := byType[t]
		if len(list) == 0 {
			continue
		}
		fmt.Fprintf(&body, "## %s\n\n", pluralLabel(t))
		sort.Slice(list, func(i, j int) bool {
			return strings.ToLower(list[i].Title) < strings.ToLower(list[j].Title)
		})
		for _, p := range list {
			// Existing entries are keyed by their wikilink form
			// (e.g. "entities/Cascade"), not the page title. Look up
			// by both so old indexes that used title-only also survive
			// the migration.
			linkKey := strings.ToLower(strings.TrimSuffix(strings.TrimPrefix(p.Path, "wiki/"), ".md"))
			titleKey := strings.ToLower(strings.TrimSpace(p.Title))
			desc, kept := descriptions[linkKey]
			if !kept {
				desc, kept = descriptions[titleKey]
			}
			if kept {
				result.DescriptionsKept++
			} else {
				result.DescriptionsBlank++
			}
			srcCount := len(p.Sources)
			line := formatIndexLine(p, desc, srcCount)
			body.WriteString(line)
			body.WriteString("\n")
		}
		body.WriteString("\n")
		result.PagesByType[t] = len(list)
	}

	out := body.String()
	result.Bytes = len(out)

	if dryRun {
		return result, nil
	}
	if err := os.MkdirAll(filepath.Dir(indexPath), 0o755); err != nil {
		return result, err
	}
	if err := os.WriteFile(indexPath, []byte(out), 0o644); err != nil {
		return result, err
	}
	return result, nil
}

// readExistingDescriptions parses any existing index.md and returns a
// folded-title → description map. Returns empty map if the file
// doesn't exist; that's a fresh-vault first run, not an error.
func readExistingDescriptions(path string) map[string]string {
	out := map[string]string{}
	f, err := os.Open(path)
	if err != nil {
		return out
	}
	defer f.Close()
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 64*1024), 4*1024*1024)
	for scanner.Scan() {
		m := existingEntryRE.FindStringSubmatch(scanner.Text())
		if m == nil {
			continue
		}
		title := strings.ToLower(strings.TrimSpace(m[1]))
		desc := strings.TrimSpace(m[2])
		if title == "" {
			continue
		}
		out[title] = desc
	}
	return out
}

// formatIndexLine emits the canonical entry shape:
//
//	- [[Title]] — description (N sources)
//
// or the description-less variant when none is preserved.
func formatIndexLine(p manifest.PageInfo, desc string, srcCount int) string {
	link := strings.TrimSuffix(strings.TrimPrefix(p.Path, "wiki/"), ".md")
	srcSuffix := ""
	if srcCount == 1 {
		srcSuffix = " (1 source)"
	} else if srcCount > 1 {
		srcSuffix = fmt.Sprintf(" (%d sources)", srcCount)
	}
	if desc != "" {
		return fmt.Sprintf("- [[%s]] — %s%s", link, desc, srcSuffix)
	}
	return fmt.Sprintf("- [[%s]]%s", link, srcSuffix)
}

func groupByType(pages []manifest.PageInfo) map[string][]manifest.PageInfo {
	out := map[string][]manifest.PageInfo{}
	for _, p := range pages {
		out[p.Type] = append(out[p.Type], p)
	}
	return out
}

func pluralLabel(t string) string {
	switch t {
	case "entity":
		return "Entities"
	case "concept":
		return "Concepts"
	case "synthesis":
		return "Synthesis"
	case "summary":
		return "Summaries"
	case "collection":
		return "Collections"
	default:
		return t
	}
}
